import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";

import { PublicHeader } from "../components/header/public-header";
import { PrivateHeader } from "../components/header/private-header";
import { Footer } from "../components/footer";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jogaí",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("jogai-app.token")?.value;
  const isAuthenticated = Boolean(token);

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
        {isAuthenticated ? <PrivateHeader /> : <PublicHeader />}
        <main className="py-10 px-5">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
